[package]
name = "guprec"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
regex = "*"
educe = "*"
rand = "*"
serde_json = "*"
serde = {version = "*", features = ["derive"]}
